//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coginov.GraphApi.Library {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coginov.GraphApi.Library.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access drive for.
        /// </summary>
        internal static string CannotAccessDrive {
            get {
                return ResourceManager.GetString("CannotAccessDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get a valid JWT to process the request.
        /// </summary>
        internal static string CannotGetJwtToken {
            get {
                return ResourceManager.GetString("CannotGetJwtToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve a refresh token.
        /// </summary>
        internal static string CannotGetRefreshToken {
            get {
                return ResourceManager.GetString("CannotGetRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read token from file.
        /// </summary>
        internal static string CannotReadTokenFile {
            get {
                return ResourceManager.GetString("CannotReadTokenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save encrytoped token to file system.
        /// </summary>
        internal static string CannotSaveToken {
            get {
                return ResourceManager.GetString("CannotSaveToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to certificateName should not be empty. Please set the CertificateName setting in the appsettings.json.
        /// </summary>
        internal static string CertificateEmpty {
            get {
                return ResourceManager.GetString("CertificateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose between using client secret or certificate. Please update appsettings.json file..
        /// </summary>
        internal static string ChooseClientOrCertificate {
            get {
                return ResourceManager.GetString("ChooseClientOrCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination folder not found.
        /// </summary>
        internal static string DestinationFolderNotFound {
            get {
                return ResourceManager.GetString("DestinationFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload complete, item ID.
        /// </summary>
        internal static string DriveItemUploadComplete {
            get {
                return ResourceManager.GetString("DriveItemUploadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uploading file.
        /// </summary>
        internal static string DriveItemUploadFailed {
            get {
                return ResourceManager.GetString("DriveItemUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded {0} bytes of {1} bytes.
        /// </summary>
        internal static string DriveItemUploadProgress {
            get {
                return ResourceManager.GetString("DriveItemUploadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting DriveItem.
        /// </summary>
        internal static string ErrorDeletingDriveItem {
            get {
                return ResourceManager.GetString("ErrorDeletingDriveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error forwarding email to recipient.
        /// </summary>
        internal static string ErrorForwardingEmail {
            get {
                return ResourceManager.GetString("ErrorForwardingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Initializing Microsoft Graph client.
        /// </summary>
        internal static string ErrorInitializingGraph {
            get {
                return ResourceManager.GetString("ErrorInitializingGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing OneDrive connection.
        /// </summary>
        internal static string ErrorInitializingODConnection {
            get {
                return ResourceManager.GetString("ErrorInitializingODConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing Sharepoint connection.
        /// </summary>
        internal static string ErrorInitializingSPConnection {
            get {
                return ResourceManager.GetString("ErrorInitializingSPConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing MS Teams connection.
        /// </summary>
        internal static string ErrorInitializingTeamsConnection {
            get {
                return ResourceManager.GetString("ErrorInitializingTeamsConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error moving DriveItem.
        /// </summary>
        internal static string ErrorMovingDriveItem {
            get {
                return ResourceManager.GetString("ErrorMovingDriveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error moving email to folder.
        /// </summary>
        internal static string ErrorMovingEmail {
            get {
                return ResourceManager.GetString("ErrorMovingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error removing email.
        /// </summary>
        internal static string ErrorRemovingEmail {
            get {
                return ResourceManager.GetString("ErrorRemovingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving AzureAd Groups.
        /// </summary>
        internal static string ErrorRetrievingAzureAdGroups {
            get {
                return ResourceManager.GetString("ErrorRetrievingAzureAdGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Retrieving Document Libraries.
        /// </summary>
        internal static string ErrorRetrievingDocLibraries {
            get {
                return ResourceManager.GetString("ErrorRetrievingDocLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving Document Ids.
        /// </summary>
        internal static string ErrorRetrievingDocumentIds {
            get {
                return ResourceManager.GetString("ErrorRetrievingDocumentIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving documents in Folder.
        /// </summary>
        internal static string ErrorRetrievingDocuments {
            get {
                return ResourceManager.GetString("ErrorRetrievingDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving Drive Item.
        /// </summary>
        internal static string ErrorRetrievingDriveItem {
            get {
                return ResourceManager.GetString("ErrorRetrievingDriveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving Drives.
        /// </summary>
        internal static string ErrorRetrievingDrives {
            get {
                return ResourceManager.GetString("ErrorRetrievingDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving account folders from Exchange.
        /// </summary>
        internal static string ErrorRetrievingExchangeFolders {
            get {
                return ResourceManager.GetString("ErrorRetrievingExchangeFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving messages from Exchange.
        /// </summary>
        internal static string ErrorRetrievingExchangeMessages {
            get {
                return ResourceManager.GetString("ErrorRetrievingExchangeMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving Exchange messages count.
        /// </summary>
        internal static string ErrorRetrievingExchangeMessagesCount {
            get {
                return ResourceManager.GetString("ErrorRetrievingExchangeMessagesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving Site Id.
        /// </summary>
        internal static string ErrorRetrievingSiteId {
            get {
                return ResourceManager.GetString("ErrorRetrievingSiteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving Sharepoint Online Sites and Document Libraries.
        /// </summary>
        internal static string ErrorRetrievingSpoSites {
            get {
                return ResourceManager.GetString("ErrorRetrievingSpoSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Retrieving Teams.
        /// </summary>
        internal static string ErrorRetrievingTeams {
            get {
                return ResourceManager.GetString("ErrorRetrievingTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving User Id.
        /// </summary>
        internal static string ErrorRetrievingUserId {
            get {
                return ResourceManager.GetString("ErrorRetrievingUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving Drive Item to file system.
        /// </summary>
        internal static string ErrorSavingDriveItem {
            get {
                return ResourceManager.GetString("ErrorSavingDriveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving Exchange message to file system.
        /// </summary>
        internal static string ErrorSavingExchangeMessage {
            get {
                return ResourceManager.GetString("ErrorSavingExchangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error searching folders in Sharepoint document library.
        /// </summary>
        internal static string ErrorSearchingFolders {
            get {
                return ResourceManager.GetString("ErrorSearchingFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending email to recipient.
        /// </summary>
        internal static string ErrorSendingEmail {
            get {
                return ResourceManager.GetString("ErrorSendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating items in Sharepoint document library.
        /// </summary>
        internal static string ErrorUpdatingSharepointItems {
            get {
                return ResourceManager.GetString("ErrorUpdatingSharepointItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists. Retrying with another name..
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving document Ids. Returning empty results.
        /// </summary>
        internal static string GraphApiExceptionReturningEmptyResult {
            get {
                return ResourceManager.GetString("GraphApiExceptionReturningEmptyResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrying in {0} seconds. Attepmt: {1}.
        /// </summary>
        internal static string GraphRetryAttempts {
            get {
                return ResourceManager.GetString("GraphRetryAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid search parameters provided.
        /// </summary>
        internal static string InvalidSearchParameters {
            get {
                return ResourceManager.GetString("InvalidSearchParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid items update parameters.
        /// </summary>
        internal static string InvalidUpdateParameters {
            get {
                return ResourceManager.GetString("InvalidUpdateParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified document libraries not found.
        /// </summary>
        internal static string LibrariesNotFound {
            get {
                return ResourceManager.GetString("LibrariesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified document library not found.
        /// </summary>
        internal static string LibraryNotFound {
            get {
                return ResourceManager.GetString("LibraryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve encrypted token, token may be unencrypted.
        /// </summary>
        internal static string TokenUnencrypted {
            get {
                return ResourceManager.GetString("TokenUnencrypted", resourceCulture);
            }
        }
    }
}
