//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coginov.GraphApi.Library {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coginov.GraphApi.Library.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access drive for.
        /// </summary>
        internal static string CannotAccessDrive {
            get {
                return ResourceManager.GetString("CannotAccessDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get a valid JWT to process the request.
        /// </summary>
        internal static string CannotGetJwtToken {
            get {
                return ResourceManager.GetString("CannotGetJwtToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve a refresh token.
        /// </summary>
        internal static string CannotGetRefreshToken {
            get {
                return ResourceManager.GetString("CannotGetRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read token from file.
        /// </summary>
        internal static string CannotReadTokenFile {
            get {
                return ResourceManager.GetString("CannotReadTokenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save encrytoped token to file system.
        /// </summary>
        internal static string CannotSaveToken {
            get {
                return ResourceManager.GetString("CannotSaveToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to certificateName should not be empty. Please set the CertificateName setting in the appsettings.json.
        /// </summary>
        internal static string CertificateEmpty {
            get {
                return ResourceManager.GetString("CertificateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose between using client secret or certificate. Please update appsettings.json file..
        /// </summary>
        internal static string ChooseClientOrCertificate {
            get {
                return ResourceManager.GetString("ChooseClientOrCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination folder not found.
        /// </summary>
        internal static string DestinationFolderNotFound {
            get {
                return ResourceManager.GetString("DestinationFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload complete, item ID.
        /// </summary>
        internal static string DriveItemUploadComplete {
            get {
                return ResourceManager.GetString("DriveItemUploadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uploading file.
        /// </summary>
        internal static string DriveItemUploadFailed {
            get {
                return ResourceManager.GetString("DriveItemUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded {0} bytes of {1} bytes.
        /// </summary>
        internal static string DriveItemUploadProgress {
            get {
                return ResourceManager.GetString("DriveItemUploadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User or Application is not authorized to download from this Drive.
        /// </summary>
        internal static string ErrorAccessDeniedToDrive {
            get {
                return ResourceManager.GetString("ErrorAccessDeniedToDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot move email to quarantine; the quarantine folder could not be established for user &apos;{User}&apos;.
        /// </summary>
        internal static string ErrorCannotMoveEmailToQuarantine {
            get {
                return ResourceManager.GetString("ErrorCannotMoveEmailToQuarantine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot move item to quarantine because the quarantine folder could not be found or created in drive &apos;{DriveId}&apos;.
        /// </summary>
        internal static string ErrorCannotMoveItemCauseFolderNotFound {
            get {
                return ResourceManager.GetString("ErrorCannotMoveItemCauseFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting DriveItem.
        /// </summary>
        internal static string ErrorDeletingDriveItem {
            get {
                return ResourceManager.GetString("ErrorDeletingDriveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore operation failed: Original DocumentId cannot be null or empty.
        /// </summary>
        internal static string ErrorDocumentIdNullOrEmpty {
            get {
                return ResourceManager.GetString("ErrorDocumentIdNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore operation failed: DriveId cannot be null or empty.
        /// </summary>
        internal static string ErrorDriveIdNullOrEmpty {
            get {
                return ResourceManager.GetString("ErrorDriveIdNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &apos;{MessageId}&apos; not found in &apos;{SourceFolder}&apos; either. The item may be permanently purged or the ID is incorrect.
        /// </summary>
        internal static string ErrorEmailNotFoundOnFolder {
            get {
                return ResourceManager.GetString("ErrorEmailNotFoundOnFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to access the application&apos;s private storage area (approot) for the drive.
        /// </summary>
        internal static string ErrorFailedToAccessAppRoot {
            get {
                return ResourceManager.GetString("ErrorFailedToAccessAppRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create quarantine folder: {InnerEx}.
        /// </summary>
        internal static string ErrorFailedToCreateQuarantineFolder {
            get {
                return ResourceManager.GetString("ErrorFailedToCreateQuarantineFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to ensure quarantine mail folder exists for user &apos;{User}&apos;.
        /// </summary>
        internal static string ErrorFailedToEnsureQuarantineFolderExists {
            get {
                return ResourceManager.GetString("ErrorFailedToEnsureQuarantineFolderExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to move DriveItem &apos;{DocumentId}&apos; to quarantine.
        /// </summary>
        internal static string ErrorFailedToMoveDriveItem {
            get {
                return ResourceManager.GetString("ErrorFailedToMoveDriveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to move message &apos;{MessageId}&apos; to quarantine.
        /// </summary>
        internal static string ErrorFailedToMoveMessage {
            get {
                return ResourceManager.GetString("ErrorFailedToMoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to resolve a valid composite Site ID from URL &apos;{SiteUrl}&apos;.
        /// </summary>
        internal static string ErrorFailedToResolveValidSiteId {
            get {
                return ResourceManager.GetString("ErrorFailedToResolveValidSiteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to restore message &apos;{MessageId}&apos; from quarantine.
        /// </summary>
        internal static string ErrorFailedToRestoreMessage {
            get {
                return ResourceManager.GetString("ErrorFailedToRestoreMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error forwarding email to recipient.
        /// </summary>
        internal static string ErrorForwardingEmail {
            get {
                return ResourceManager.GetString("ErrorForwardingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting Drive Item Metadata.
        /// </summary>
        internal static string ErrorGettingDriveItemMetadata {
            get {
                return ResourceManager.GetString("ErrorGettingDriveItemMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph API error while moving message &apos;{MessageId}&apos; to quarantine. Code: {ErrorCode}, Message: {ErrorMessage}.
        /// </summary>
        internal static string ErrorGraphApiErrorMovingMessage {
            get {
                return ResourceManager.GetString("ErrorGraphApiErrorMovingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph API error while restoring message &apos;{MessageId}&apos;. Code: {ErrorCode}, Message: {ErrorMessage}.
        /// </summary>
        internal static string ErrorGraphApiErrorWhileRestoringMessage {
            get {
                return ResourceManager.GetString("ErrorGraphApiErrorWhileRestoringMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph API error during restore process for &apos;{DocumentId}&apos;. Code: {ErrorCode}, Message: {ErrorMessage}.
        /// </summary>
        internal static string ErrorGraphApiRestoreProcessFail {
            get {
                return ResourceManager.GetString("ErrorGraphApiRestoreProcessFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot restore item. GraphServiceClient is not initialized.
        /// </summary>
        internal static string ErrorGraphServiceClientNotInitialized {
            get {
                return ResourceManager.GetString("ErrorGraphServiceClientNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Initializing Microsoft Graph client.
        /// </summary>
        internal static string ErrorInitializingGraph {
            get {
                return ResourceManager.GetString("ErrorInitializingGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing OneDrive connection.
        /// </summary>
        internal static string ErrorInitializingODConnection {
            get {
                return ResourceManager.GetString("ErrorInitializingODConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing Sharepoint connection.
        /// </summary>
        internal static string ErrorInitializingSPConnection {
            get {
                return ResourceManager.GetString("ErrorInitializingSPConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing MS Teams connection.
        /// </summary>
        internal static string ErrorInitializingTeamsConnection {
            get {
                return ResourceManager.GetString("ErrorInitializingTeamsConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore failed: siteUrl, driveId, and originalDocumentId are all required.
        /// </summary>
        internal static string ErrorMandatoryParametersAreMissing {
            get {
                return ResourceManager.GetString("ErrorMandatoryParametersAreMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore failed: driveId, documentId, and originalParentFolderId are all required.
        /// </summary>
        internal static string ErrorMandatoryParametersAreMissingForDriveItem {
            get {
                return ResourceManager.GetString("ErrorMandatoryParametersAreMissingForDriveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &apos;{MessageId}&apos; not found in &apos;{SourceFolder}&apos;. Proceeding to check recoverable items.
        /// </summary>
        internal static string ErrorMessageIdNotFoundOnFolder {
            get {
                return ResourceManager.GetString("ErrorMessageIdNotFoundOnFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore email failed: userAccount and messageId are required.
        /// </summary>
        internal static string ErrorMissingParametersRequiredToRestoreEmail {
            get {
                return ResourceManager.GetString("ErrorMissingParametersRequiredToRestoreEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot restore email &apos;{MessageId}&apos;: Original parent folder ID was not provided.
        /// </summary>
        internal static string ErrorMissingParentFolderIdOnRestore {
            get {
                return ResourceManager.GetString("ErrorMissingParentFolderIdOnRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error moving DriveItem.
        /// </summary>
        internal static string ErrorMovingDriveItem {
            get {
                return ResourceManager.GetString("ErrorMovingDriveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error moving email to folder.
        /// </summary>
        internal static string ErrorMovingEmail {
            get {
                return ResourceManager.GetString("ErrorMovingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received a null stream from recycle bin for Site ID &apos;{SiteId}&apos;.
        /// </summary>
        internal static string ErrorNullStreamReceivedFromReciclerBin {
            get {
                return ResourceManager.GetString("ErrorNullStreamReceivedFromReciclerBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot restore email; the quarantine folder could not be found for user &apos;{User}&apos;.
        /// </summary>
        internal static string ErrorQuarantineFolderNotFoundOnRestore {
            get {
                return ResourceManager.GetString("ErrorQuarantineFolderNotFoundOnRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error removing email.
        /// </summary>
        internal static string ErrorRemovingEmail {
            get {
                return ResourceManager.GetString("ErrorRemovingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph API error while restoring document &apos;{DocumentId}&apos;. Code: {ErrorCode}, Message: {ErrorMessage}.
        /// </summary>
        internal static string ErrorRestoringDocument {
            get {
                return ResourceManager.GetString("ErrorRestoringDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving AzureAd Groups.
        /// </summary>
        internal static string ErrorRetrievingAzureAdGroups {
            get {
                return ResourceManager.GetString("ErrorRetrievingAzureAdGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Retrieving Document Libraries.
        /// </summary>
        internal static string ErrorRetrievingDocLibraries {
            get {
                return ResourceManager.GetString("ErrorRetrievingDocLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving Document Ids.
        /// </summary>
        internal static string ErrorRetrievingDocumentIds {
            get {
                return ResourceManager.GetString("ErrorRetrievingDocumentIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving documents in Folder.
        /// </summary>
        internal static string ErrorRetrievingDocuments {
            get {
                return ResourceManager.GetString("ErrorRetrievingDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving Drive Item.
        /// </summary>
        internal static string ErrorRetrievingDriveItem {
            get {
                return ResourceManager.GetString("ErrorRetrievingDriveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving Drives.
        /// </summary>
        internal static string ErrorRetrievingDrives {
            get {
                return ResourceManager.GetString("ErrorRetrievingDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving account folders from Exchange.
        /// </summary>
        internal static string ErrorRetrievingExchangeFolders {
            get {
                return ResourceManager.GetString("ErrorRetrievingExchangeFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving messages from Exchange.
        /// </summary>
        internal static string ErrorRetrievingExchangeMessages {
            get {
                return ResourceManager.GetString("ErrorRetrievingExchangeMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving Exchange messages count.
        /// </summary>
        internal static string ErrorRetrievingExchangeMessagesCount {
            get {
                return ResourceManager.GetString("ErrorRetrievingExchangeMessagesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving messages from Exchange NextLink.
        /// </summary>
        internal static string ErrorRetrievingExchangeMessagesFromNextLink {
            get {
                return ResourceManager.GetString("ErrorRetrievingExchangeMessagesFromNextLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving Site Id.
        /// </summary>
        internal static string ErrorRetrievingSiteId {
            get {
                return ResourceManager.GetString("ErrorRetrievingSiteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving Sharepoint Online Sites and Document Libraries.
        /// </summary>
        internal static string ErrorRetrievingSpoSites {
            get {
                return ResourceManager.GetString("ErrorRetrievingSpoSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Retrieving Teams.
        /// </summary>
        internal static string ErrorRetrievingTeams {
            get {
                return ResourceManager.GetString("ErrorRetrievingTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving User Id.
        /// </summary>
        internal static string ErrorRetrievingUserId {
            get {
                return ResourceManager.GetString("ErrorRetrievingUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving Drive Item to file system.
        /// </summary>
        internal static string ErrorSavingDriveItem {
            get {
                return ResourceManager.GetString("ErrorSavingDriveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving Exchange message to file system.
        /// </summary>
        internal static string ErrorSavingExchangeMessage {
            get {
                return ResourceManager.GetString("ErrorSavingExchangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error searching folders in Sharepoint document library.
        /// </summary>
        internal static string ErrorSearchingFolders {
            get {
                return ResourceManager.GetString("ErrorSearchingFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending email to recipient.
        /// </summary>
        internal static string ErrorSendingEmail {
            get {
                return ResourceManager.GetString("ErrorSendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error ensuring quarantine folder: {ex}.
        /// </summary>
        internal static string ErrorUnexpectedEnsuringFolder {
            get {
                return ResourceManager.GetString("ErrorUnexpectedEnsuringFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while getting Message information.
        /// </summary>
        internal static string ErrorUnexpectedErrorFoundGettingMessage {
            get {
                return ResourceManager.GetString("ErrorUnexpectedErrorFoundGettingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while checking &apos;{SourceFolder}&apos;.
        /// </summary>
        internal static string ErrorUnexpectedErrorWhileCheckingSource {
            get {
                return ResourceManager.GetString("ErrorUnexpectedErrorWhileCheckingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while restoring document &apos;{DocumentId}&apos;.
        /// </summary>
        internal static string ErrorUnexpectedRestoringDocument {
            get {
                return ResourceManager.GetString("ErrorUnexpectedRestoringDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating items in Sharepoint document library.
        /// </summary>
        internal static string ErrorUpdatingSharepointItems {
            get {
                return ResourceManager.GetString("ErrorUpdatingSharepointItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists. Retrying with another name..
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph API error while restoring DriveItem &apos;{DocumentId}&apos;. Code: {ErrorCode}, Message: {ErrorMessage}.
        /// </summary>
        internal static string GraphApiErrorWhileRestoringDriveItem {
            get {
                return ResourceManager.GetString("GraphApiErrorWhileRestoringDriveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving document Ids. Returning empty results.
        /// </summary>
        internal static string GraphApiExceptionReturningEmptyResult {
            get {
                return ResourceManager.GetString("GraphApiExceptionReturningEmptyResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrying in {0} seconds. Attepmt: {1}.
        /// </summary>
        internal static string GraphRetryAttempts {
            get {
                return ResourceManager.GetString("GraphRetryAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to restore item &apos;{DocumentId}&apos; in drive &apos;{DriveId}&apos; to its original parent folder &apos;{ParentId}&apos;.
        /// </summary>
        internal static string InfoAttemptingToRestoreDriveItem {
            get {
                return ResourceManager.GetString("InfoAttemptingToRestoreDriveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to restore item &apos;{DocumentId}&apos; from site &apos;{SiteUrl}&apos;.
        /// </summary>
        internal static string InfoAttemptingToRestoreItem {
            get {
                return ResourceManager.GetString("InfoAttemptingToRestoreItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to restore email ID &apos;{MessageId}&apos; for user &apos;{User}&apos; to &apos;{DestinationFolder}&apos;.
        /// </summary>
        internal static string InfoAttentingToRestoreEmail {
            get {
                return ResourceManager.GetString("InfoAttentingToRestoreEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully restored document &apos;{DocumentId}&apos;. New ID (if changed) is &apos;{NewId}&apos;, restored to &apos;{ParentPath}&apos;.
        /// </summary>
        internal static string InfoDocumentRestoredSuccessfully {
            get {
                return ResourceManager.GetString("InfoDocumentRestoredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully restored email from &apos;{SourceFolder}&apos;.
        /// </summary>
        internal static string InfoEmailRestoredSuccessfully {
            get {
                return ResourceManager.GetString("InfoEmailRestoredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found existing quarantine folder &apos;{FolderName}&apos; in drive &apos;{DriveId}&apos;.
        /// </summary>
        internal static string InfoFoundExistingQuarantineFolder {
            get {
                return ResourceManager.GetString("InfoFoundExistingQuarantineFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found existing quarantine mail folder &apos;{FolderName}&apos; for user &apos;{User}&apos;.
        /// </summary>
        internal static string InfoFoundExistingQuarantineMailFolder {
            get {
                return ResourceManager.GetString("InfoFoundExistingQuarantineMailFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully moved item &apos;{DocumentId}&apos; to quarantine folder.
        /// </summary>
        internal static string InfoItemMovedSuccessfullyToQuarantine {
            get {
                return ResourceManager.GetString("InfoItemMovedSuccessfullyToQuarantine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully restored item &apos;{DocumentId}&apos; to its original location.
        /// </summary>
        internal static string InfoItemRestoredSucessfully {
            get {
                return ResourceManager.GetString("InfoItemRestoredSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully moved message &apos;{MessageId}&apos; to quarantine for user &apos;{User}&apos;.
        /// </summary>
        internal static string InfoMessageMovedSuccessfullyToQuarantine {
            get {
                return ResourceManager.GetString("InfoMessageMovedSuccessfullyToQuarantine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created quarantine folder &apos;{FolderName}&apos; and restricted access.
        /// </summary>
        internal static string InfoQuarantineFolderCreatedSucessfully {
            get {
                return ResourceManager.GetString("InfoQuarantineFolderCreatedSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarantine folder &apos;{folderName}&apos; not found in drive &apos;{driveId}&apos;. Creating it now.
        /// </summary>
        internal static string InfoQuarantineFolderNotFound {
            get {
                return ResourceManager.GetString("InfoQuarantineFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarantine mail folder &apos;{FolderName}&apos; not found for user &apos;{User}&apos;. Creating it now.
        /// </summary>
        internal static string InfoQuarantineMailFolderNotFound {
            get {
                return ResourceManager.GetString("InfoQuarantineMailFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolved composite Site ID: {SiteId}.
        /// </summary>
        internal static string InfoResolvedValidSiteId {
            get {
                return ResourceManager.GetString("InfoResolvedValidSiteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore command sent successfully for original item ID &apos;{DocumentId}&apos;.
        /// </summary>
        internal static string InfoRestoreCommandSentSuccessfully {
            get {
                return ResourceManager.GetString("InfoRestoreCommandSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to restore document with original ID &apos;{DocumentId}&apos; from drive &apos;{DriveId}&apos;.
        /// </summary>
        internal static string InfoRestoringDocument {
            get {
                return ResourceManager.GetString("InfoRestoringDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created hidden quarantine mail folder.
        /// </summary>
        internal static string InfoSuccessfullyCreatedHiddenMailFolder {
            get {
                return ResourceManager.GetString("InfoSuccessfullyCreatedHiddenMailFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully restored message &apos;{MessageId}&apos; to folder &apos;{DestinationId}&apos;.
        /// </summary>
        internal static string InfoSuccessfullyRestoredMessage {
            get {
                return ResourceManager.GetString("InfoSuccessfullyRestoredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Exchange Connection.
        /// </summary>
        internal static string InitializingExchangeConnection {
            get {
                return ResourceManager.GetString("InitializingExchangeConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing GraphApi.
        /// </summary>
        internal static string InitializingGraphApi {
            get {
                return ResourceManager.GetString("InitializingGraphApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing MsTeams Connection.
        /// </summary>
        internal static string InitializingMsTeamsConnection {
            get {
                return ResourceManager.GetString("InitializingMsTeamsConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing OneDrive Connection.
        /// </summary>
        internal static string InitializingOneDriveConnection {
            get {
                return ResourceManager.GetString("InitializingOneDriveConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing SharePointOnline Connection.
        /// </summary>
        internal static string InitializingSharePointOnlineConnection {
            get {
                return ResourceManager.GetString("InitializingSharePointOnlineConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid search parameters provided.
        /// </summary>
        internal static string InvalidSearchParameters {
            get {
                return ResourceManager.GetString("InvalidSearchParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid items update parameters.
        /// </summary>
        internal static string InvalidUpdateParameters {
            get {
                return ResourceManager.GetString("InvalidUpdateParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified document libraries not found.
        /// </summary>
        internal static string LibrariesNotFound {
            get {
                return ResourceManager.GetString("LibrariesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified document library not found.
        /// </summary>
        internal static string LibraryNotFound {
            get {
                return ResourceManager.GetString("LibraryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation time out, cannot get a valid JWT to process the request.
        /// </summary>
        internal static string TimeOutGettingJwtToken {
            get {
                return ResourceManager.GetString("TimeOutGettingJwtToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve encrypted token, token may be unencrypted.
        /// </summary>
        internal static string TokenUnencrypted {
            get {
                return ResourceManager.GetString("TokenUnencrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while restoring document &apos;{DocumentId}&apos;.
        /// </summary>
        internal static string UnexpectedErrorWhileRestoringDocument {
            get {
                return ResourceManager.GetString("UnexpectedErrorWhileRestoringDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find item with original DriveItem ID &apos;{DocumentId}&apos; in the recycle bin for Site &apos;{SiteId}&apos;.
        /// </summary>
        internal static string WarningCouldNotFindItem {
            get {
                return ResourceManager.GetString("WarningCouldNotFindItem", resourceCulture);
            }
        }
    }
}
