//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coginov.GraphApi.Library {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coginov.GraphApi.Library.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access drive for.
        /// </summary>
        internal static string CannotAccessDrive {
            get {
                return ResourceManager.GetString("CannotAccessDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Initializing Microsoft Graph client.
        /// </summary>
        internal static string ErrorInitializingGraph {
            get {
                return ResourceManager.GetString("ErrorInitializingGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing OneDrive connection.
        /// </summary>
        internal static string ErrorInitializingODConnection {
            get {
                return ResourceManager.GetString("ErrorInitializingODConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing Sharepoint connection.
        /// </summary>
        internal static string ErrorInitializingSPConnection {
            get {
                return ResourceManager.GetString("ErrorInitializingSPConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing MS Teams connection.
        /// </summary>
        internal static string ErrorInitializingTeamsConnection {
            get {
                return ResourceManager.GetString("ErrorInitializingTeamsConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving Document Ids.
        /// </summary>
        internal static string ErrorRetrievingDocumentIds {
            get {
                return ResourceManager.GetString("ErrorRetrievingDocumentIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving Drive Item.
        /// </summary>
        internal static string ErrorRetrievingDriveItem {
            get {
                return ResourceManager.GetString("ErrorRetrievingDriveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving Drives.
        /// </summary>
        internal static string ErrorRetrievingDrives {
            get {
                return ResourceManager.GetString("ErrorRetrievingDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving account folders from Exchange.
        /// </summary>
        internal static string ErrorRetrievingExchangeFolders {
            get {
                return ResourceManager.GetString("ErrorRetrievingExchangeFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving messages from Exchange.
        /// </summary>
        internal static string ErrorRetrievingExchangeMessages {
            get {
                return ResourceManager.GetString("ErrorRetrievingExchangeMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving Site Id.
        /// </summary>
        internal static string ErrorRetrievingSiteId {
            get {
                return ResourceManager.GetString("ErrorRetrievingSiteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving User Id.
        /// </summary>
        internal static string ErrorRetrievingUserId {
            get {
                return ResourceManager.GetString("ErrorRetrievingUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving Drive Item to file system.
        /// </summary>
        internal static string ErrorSavingDriveItem {
            get {
                return ResourceManager.GetString("ErrorSavingDriveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving Exchange message to file system.
        /// </summary>
        internal static string ErrorSavingExchangeMessage {
            get {
                return ResourceManager.GetString("ErrorSavingExchangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrying in {0} seconds. Attepmt: {1}.
        /// </summary>
        internal static string GraphRetryAttempts {
            get {
                return ResourceManager.GetString("GraphRetryAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified document library not found.
        /// </summary>
        internal static string LibraryNotFound {
            get {
                return ResourceManager.GetString("LibraryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified libraries not found, selecting all Document Libraries as default.
        /// </summary>
        internal static string NoLibraryFound {
            get {
                return ResourceManager.GetString("NoLibraryFound", resourceCulture);
            }
        }
    }
}
