# Variable 'buildNumber' was defined in the Variables tab
trigger:
  branches:
    include:
    - refs/heads/main
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: NuGetToolInstaller@1
    displayName: Install Version NuGet 6.1.0
    inputs:
      versionSpec: 6.1.0
  - task: NuGetCommand@2
    displayName: NuGet restore
  - task: PowerShell@2
    displayName: Get Version From File in Gitlab
    inputs:
      filePath: Coginov.GraphApi.Library.Azure.Pipelines/getversionfromfileprod.ps1
  - task: VSBuild@1
    displayName: Build Coginov GraphApi Library
    inputs:
      msbuildArgs: /p:Version=$(buildNumber)
  - task: AzureKeyVault@2
    displayName: Get Certificate From Azure Key Vault
    inputs:
      ConnectedServiceName: eec4c4ca-8ef2-4a3e-ab25-34cb990a06ca
      KeyVaultName: kv-dev-canadaeast
  - task: PowerShell@2
    displayName: Sign Coginov GraphApi Library
    inputs:
      filePath: Coginov.GraphApi.Library.Azure.Pipelines/signcoginovgraphapilibrary.ps1
      arguments: -ArtefactFolder "$(System.DefaultWorkingDirectory)" -base64 "$(CoginovCodeSigining)"
  - task: NuGetCommand@2
    displayName: NuGet pack for Coginov GraphApi Library
    inputs:
      command: pack
      versioningScheme: byEnvVar
      versionEnvVar: buildNumber
  - task: PublishBuildArtifacts@1
    displayName: Publish Nuget  Package of Coginov GraphApi Library in Local Repository
  - task: NuGetCommand@2
    displayName: NuGet push Coginov GraphApi Library
    inputs:
      command: push
      searchPatternPush: $(Build.ArtifactStagingDirectory)/*.nupkg
      feedPublish: 03f872cd-d7c9-4c7c-a4db-45bf005bf779
...
